name: Build MAUI Windows

on:
  push:
      branches:    
        - '**'        # matches every branch
  pull_request:
      branches:
        - main
        - release
        - dev

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install MAUI Workloads
        run: dotnet workload install maui-windows

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the application
        run: dotnet build -f net8.0-windows --configuration Release --no-restore

      - name: Run unit tests (Windows target)
        run: dotnet test -f net8.0-windows --configuration Release --no-restore --no-build --verbosity normal
